#pragma once
#include <Box2D/Common/b2Settings.h>

#define SUB_ENTITIES_COUNT 10
#define FIXTURE_ENTITIES_COUNT 10
#define SPECIFIC_HOSTILE_ENTITIES_COUNT 5
#define CONCURRENT_TREES_COUNT 5
#define ITEMS_INSIDE_COUNT 20

#define COLLIDERS_COUNT 5
#define CONVEX_POLYS_COUNT 5 
#define CONVEX_POLY_VERTEX_COUNT b2_maxPolygonVertices