#pragma once
#include <Box2D/Common/b2Settings.h>

#define SUB_ENTITIES_COUNT 10
#define FIXTURE_ENTITIES_COUNT 10
#define SPECIFIC_HOSTILE_ENTITIES_COUNT 5
#define CONCURRENT_TREES_COUNT 5
#define ITEMS_INSIDE_COUNT 20

#define COLLIDERS_COUNT 5
#define CONVEX_POLYS_COUNT 5 
#define CONVEX_POLY_VERTEX_COUNT b2_maxPolygonVertices

#define RECOIL_PLAYER_OFFSET_COUNT 50
#define ONLY_PICK_THESE_ITEMS_COUNT 20
#define MELEE_OFFSET_POSITIONS_COUNT 20
#define MOVEMENT_RESPONSE_RECEIVERS_COUNT 2

#define NICKNAME_LENGTH 50

#define RENDERING_POLYGON_INDEX_COUNT 20
#define RENDERING_POLYGON_VERTEX_COUNT 20
#define RENDERING_POLYGON_TRIANGULATED_VERTEX_COUNT 20

#define OWNER_FRICTION_GROUNDS_COUNT 10