bool DRAW_FREE_SPACE_INSIDE_CONTAINER_ICONS = true;
bool DEBUG_DRAW_COLINEARIZATION = false;
bool DEBUG_DRAW_RECOIL_CROSSHAIR = false; // init only
bool DEBUG_DRAW_FORCES = false;
bool DEBUG_DRAW_FRICTION_FIELD_COLLISIONS_OF_ENTERING = false;