#pragma once

namespace assets {
	enum shader_id {
		DEFAULT_VERTEX,
		DEFAULT_FRAGMENT,
		DEFAULT_HIGHLIGHT_VERTEX,
		DEFAULT_HIGHLIGHT_FRAGMENT,
		CIRCULAR_BARS_VERTEX,
		CIRCULAR_BARS_FRAGMENT,
		FULLSCREEN_VERTEX,
		FULLSCREEN_FRAGMENT
	};
}