#pragma once

namespace assets {
	enum class shader_id {
		INVALID,

		DEFAULT_VERTEX,
		DEFAULT_FRAGMENT,
		DEFAULT_ILLUMINATED_VERTEX,
		DEFAULT_ILLUMINATED_FRAGMENT,
		LIGHT_VERTEX,
		LIGHT_FRAGMENT,
		PURE_COLOR_HIGHLIGHT_VERTEX,
		PURE_COLOR_HIGHLIGHT_FRAGMENT,
		CIRCULAR_BARS_VERTEX,
		CIRCULAR_BARS_FRAGMENT,
		FULLSCREEN_VERTEX,
		FULLSCREEN_FRAGMENT
	};
}