#include "drag_and_drop.h"
#include "slot_button.h"
#include "item_button.h"
#include "game/detail/item_slot_transfer_request.h"
#include "game/components/item_component.h"
#include "game/detail/inventory_utils.h"
#include "game/transcendental/entity_id.h"
#include "augs/ensure.h"