#pragma once

enum class processing_subjects {
	// GEN INTROSPECTOR enum class processing_subjects
	WITH_ANIMATION,
	WITH_BEHAVIOUR_TREE,
	WITH_CAR,
	WITH_CROSSHAIR,
	WITH_DAMAGE,
	WITH_DRIVER,
	WITH_FORCE_JOINT,
	WITH_ITEM_SLOT_TRANSFERS,
	WITH_INTERPOLATION,
	WITH_MELEE,
	WITH_HAND_FUSE,
	WITH_GUN,
	WITH_MOVEMENT,
	WITH_SOUND_EXISTENCE,
	WITH_PATHFINDING,
	WITH_POSITION_COPYING,
	WITH_SENTIENCE,
	WITH_TRACE,
	WITH_ENABLED_PAST_CONTAGIOUS,
	WITH_LIGHT,

	COUNT
	// END GEN INTROSPECTOR
};
