#pragma once

enum class render_layer {
	// GEN INTROSPECTOR enum class render_layer
	INVALID,

	DISABLED,

	GROUND,
	GROUND_DECALS,
	LYING_CORPSES,

	PLANTED_ITEMS,
	OBSTACLES_UNDER_MISSILES,
	MISSILES,
	SOLID_OBSTACLES,
	REMNANTS,
	ITEMS_ON_GROUND,
	SENTIENCES,
	FOREGROUND,
	FOREGROUND_GLOWS,
	/*
		Bullet marks on walls. Drawn at the very end of the FOREGROUND buffer,
		so that they are visible above every physical body, including FOREGROUND walls.
	*/
	SURFACE_DECALS,

	DIM_WANDERING_PIXELS,
	CONTINUOUS_SOUNDS,
	CONTINUOUS_PARTICLES,
	ILLUMINATING_WANDERING_PIXELS,
	LIGHTS,
	AREA_MARKERS,
	POINT_MARKERS,
	AREA_SENSORS,
	CALLOUT_MARKERS,
	CAMERA_ZOOM_MARKERS,

	COUNT
	// END GEN INTROSPECTOR
};