#pragma once

enum item_category {
	//ITEM = 1 << 0,
	RAIL_ATTACHMENT = 1 << 1,
	BARREL_ATTACHMENT = 1 << 2,
	SHOULDER_CONTAINER = 1 << 3,
	TORSO_ARMOR = 1 << 4,
	MAGAZINE = 1 << 5,
	SHOT_CHARGE = 1 << 6,
};

enum class slot_function {
	INVALID,

	ITEM_DEPOSIT,

	GUN_CHAMBER,
	GUN_DETACHABLE_MAGAZINE,
	GUN_CHAMBER_MAGAZINE,
	GUN_RAIL,
	GUN_BARREL,

	PRIMARY_HAND,
	SECONDARY_HAND,
	
	SHOULDER_SLOT,
	TORSO_ARMOR_SLOT
};

enum item_transfer_result {
	INVALID_SLOT_OR_UNOWNED_ROOT,

	/* returned by containment_result */
	THE_SAME_SLOT,
	INCOMPATIBLE_CATEGORIES,
	INSUFFICIENT_SPACE,
	NO_SLOT_AVAILABLE,

	SUCCESSFUL_TRANSFER,
	UNMOUNT_BEFOREHAND,
};