#pragma once
#include "test_scenes/test_id_to_pool_id.h"

enum class test_scene_image_id {
	// GEN INTROSPECTOR enum class test_scene_image_id
	BLANK = 0,

	CRATE,

	TRUCK_INSIDE,
	TRUCK_FRONT,

	JMIX114,

	TEST_CROSSHAIR,

	SMOKE_1,
	SMOKE_2,
	SMOKE_3,
	SMOKE_4,
	SMOKE_5,
	SMOKE_6,

	PIXEL_THUNDER_1,
	PIXEL_THUNDER_2,
	PIXEL_THUNDER_3,
	PIXEL_THUNDER_4,
	PIXEL_THUNDER_5,

	ASSAULT_RIFLE,
	BILMER2000,
	KEK9,
	URBAN_CYAN_MACHETE,

	VINDICATOR_SHOOT_1,
	VINDICATOR_SHOOT_2,
	VINDICATOR_SHOOT_3,
	VINDICATOR_SHOOT_4,
	VINDICATOR_SHOOT_5,
	VINDICATOR_SHOOT_6,
	VINDICATOR_SHOOT_7,
	VINDICATOR_SHOOT_8,
	VINDICATOR_SHOOT_9,
	VINDICATOR_SHOOT_10,
	VINDICATOR_SHOOT_11,
	VINDICATOR_SHOOT_12,
	VINDICATOR_SHOOT_13,
	VINDICATOR_SHOOT_14,
	VINDICATOR_SHOOT_15,
	VINDICATOR_SHOOT_16,
	VINDICATOR_SHOOT_17,
	VINDICATOR_SHOOT_18,
	VINDICATOR_SHOOT_19,

	DATUM_GUN_SHOOT_1,
	DATUM_GUN_SHOOT_2,
	DATUM_GUN_SHOOT_3,
	DATUM_GUN_SHOOT_4,
	DATUM_GUN_SHOOT_5,
	DATUM_GUN_SHOOT_6,
	DATUM_GUN_SHOOT_7,
	DATUM_GUN_SHOOT_8,

	SOIL,
	FLOOR,

	SAMPLE_MAGAZINE,
	SMALL_MAGAZINE,
	ROUND_TRACE,
	ELECTRIC_MISSILE,
	PINK_CHARGE,
	PINK_SHELL,
	CYAN_CHARGE,
	CYAN_SHELL,
	RED_CHARGE,
	RED_SHELL,
	GREEN_CHARGE,
	GREEN_SHELL,
	BACKPACK,
	BROWN_BACKPACK,

	HAVE_A_PLEASANT,
	AWAKENING,
	METROPOLIS,

	BRICK_WALL,
	ROAD,
	ROAD_FRONT_DIRT,

	CAST_BLINK_1,
	CAST_BLINK_2,
	CAST_BLINK_3,
	CAST_BLINK_4,
	CAST_BLINK_5,
	CAST_BLINK_6,
	CAST_BLINK_7,
	CAST_BLINK_8,
	CAST_BLINK_9,
	CAST_BLINK_10,
	CAST_BLINK_11,
	CAST_BLINK_12,
	CAST_BLINK_13,
	CAST_BLINK_14,
	CAST_BLINK_15,
	CAST_BLINK_16,
	CAST_BLINK_17,
	CAST_BLINK_18,
	CAST_BLINK_19,

	SILVER_TROUSERS_1,
	SILVER_TROUSERS_2,
	SILVER_TROUSERS_3,
	SILVER_TROUSERS_4,

	SILVER_TROUSERS_STRAFE_1,
	SILVER_TROUSERS_STRAFE_2,
	SILVER_TROUSERS_STRAFE_3,
	SILVER_TROUSERS_STRAFE_4,
	SILVER_TROUSERS_STRAFE_5,
	SILVER_TROUSERS_STRAFE_6,
	SILVER_TROUSERS_STRAFE_7,
	SILVER_TROUSERS_STRAFE_8,

	METROPOLIS_CHARACTER_BARE_1,
	METROPOLIS_CHARACTER_BARE_2,
	METROPOLIS_CHARACTER_BARE_3,
	METROPOLIS_CHARACTER_BARE_4,
	METROPOLIS_CHARACTER_BARE_5,

	METROPOLIS_CHARACTER_AKIMBO_1,
	METROPOLIS_CHARACTER_AKIMBO_2,
	METROPOLIS_CHARACTER_AKIMBO_3,
	METROPOLIS_CHARACTER_AKIMBO_4,
	METROPOLIS_CHARACTER_AKIMBO_5,

	RESISTANCE_CHARACTER_BARE_1,
	RESISTANCE_CHARACTER_BARE_2,
	RESISTANCE_CHARACTER_BARE_3,
	RESISTANCE_CHARACTER_BARE_4,
	RESISTANCE_CHARACTER_BARE_5,

	RESISTANCE_CHARACTER_RIFLE_1,
	RESISTANCE_CHARACTER_RIFLE_2,
	RESISTANCE_CHARACTER_RIFLE_3,
	RESISTANCE_CHARACTER_RIFLE_4,
	RESISTANCE_CHARACTER_RIFLE_5,

	RESISTANCE_CHARACTER_RIFLE_SHOOT_1,
	RESISTANCE_CHARACTER_RIFLE_SHOOT_2,
	RESISTANCE_CHARACTER_RIFLE_SHOOT_3,
	RESISTANCE_CHARACTER_RIFLE_SHOOT_4,
	RESISTANCE_CHARACTER_RIFLE_SHOOT_5,

	METROPOLIS_HEAD,
	RESISTANCE_HEAD,

	TRUCK_ENGINE,

	HEALTH_ICON,
	PERSONAL_ELECTRICITY_ICON,
	CONSCIOUSNESS_ICON,

	AMPLIFIER_ARM,

	SPELL_HASTE_ICON,
	SPELL_ELECTRIC_SHIELD_ICON,
	SPELL_ELECTRIC_TRIAD_ICON,
	SPELL_FURY_OF_THE_AEONS_ICON,
	SPELL_ULTIMATE_WRATH_OF_THE_AEONS_ICON,
	SPELL_EXALTATION_ICON,
	SPELL_ECHOES_OF_THE_HIGHER_REALMS_ICON,

	PERK_HASTE_ICON,
	PERK_ELECTRIC_SHIELD_ICON,

	FORCE_GRENADE,
	PED_GRENADE,
	INTERFERENCE_GRENADE,

	FORCE_GRENADE_RELEASED,
	PED_GRENADE_RELEASED,
	INTERFERENCE_GRENADE_RELEASED,
	FORCE_ROCKET,

	COUNT
	// END GEN INTROSPECTOR
};

inline auto to_image_id(const test_scene_image_id id) {
	return to_pool_id<assets::image_id>(id);
}
