#pragma once

enum class test_static_lights {
	// GEN INTROSPECTOR enum class test_static_lights
	POINT_LIGHT,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_static_decorations {
	// GEN INTROSPECTOR enum class test_static_decorations
	SOIL,
	ROAD_DIRT,
	ROAD,
	CYAN_FLOOR,
	WATER_ROOM_FLOOR,

	HAVE_A_PLEASANT,
	AWAKENING,
	WELCOME_TO_METROPOLIS,

	SNACKBAR_CAPTION,

	AQUARIUM_BOTTOM_LAMP_LIGHT,
	AQUARIUM_BOTTOM_LAMP_BODY,

	AQUARIUM_HALOGEN_1_LIGHT,
	AQUARIUM_HALOGEN_1_BODY,

	AQUARIUM_SAND_1,
	AQUARIUM_SAND_2,

	DUNE_BIG,
	DUNE_SMALL,

	AQUARIUM_SAND_EDGE,
	AQUARIUM_SAND_CORNER,

	WATER_COLOR_OVERLAY,
	LAB_WALL_FOREGROUND,
	LAB_WALL_A2_FOREGROUND,

	ROTATING_FAN,

	FERN,
	FLOWERBED_CYAN,
	FLOWERBED_ROSES,
	FLOWERPOT_ORANGE,
	ROBOWORKER,

	DEV_FLOOR_32,
	DEV_FLOOR_64,
	DEV_FLOOR_128,
	DEV_FLOOR_256,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_controlled_characters {
	// GEN INTROSPECTOR enum class test_controlled_characters
	METROPOLIS_SOLDIER,
	RESISTANCE_SOLDIER,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_plain_sprited_bodies {
	// GEN INTROSPECTOR enum class test_plain_sprited_bodies
	CRATE,
	HARD_WOODEN_WALL,
	AQUARIUM_GLASS,

	AQUARIUM_GLASS_START,

	LAB_WALL,
	LAB_WALL_SMOOTH_END,
	LAB_WALL_CORNER_CUT,
	LAB_WALL_CORNER_SQUARE,

	SNACKBAR,

	DETACHED_METROPOLIS_HEAD,
	DETACHED_RESISTANCE_HEAD,

	BOX_COLLIDER_WOOD,
	BOX_COLLIDER_METAL,
	BOX_COLLIDER_GLASS,
	BOX_COLLIDER_VENT,

	TRIANGLE_COLLIDER_WOOD,
	TRIANGLE_COLLIDER_METAL,
	TRIANGLE_COLLIDER_GLASS,
	TRIANGLE_COLLIDER_VENT,

	DEV_WALL_32,
	DEV_WALL_64,
	DEV_WALL_128,
	DEV_WALL_256,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_shootable_weapons {
	// GEN INTROSPECTOR enum class test_shootable_weapons
	BILMER2000,
	BAKA47,
	LEWS,
	KEK9,
	SN69,
	AO44,
	CALICO,
	WARX,
	PRO90,
	AMPLIFIER_ARM,
	DATUM,
	ELON,
	BLUNAZ,
	GRADOBICIE,
	BULWARK,
	ZAMIEC,
	SZTURM,
	DEAGLE,
	AWKA,
	BULLDUP2000,
	GALILEA,
	HUNTER,
	CYBERSPRAY,
	COVERT,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_melee_weapons {
	// GEN INTROSPECTOR enum class test_melee_weapons
	FURY_THROWER,
	ELECTRIC_RAPIER,
	CYAN_SCYTHE,
	POSEIDON,
	YELLOW_DAGGER,

	ASSAULT_RATTLE,
	MINI_KNIFE,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_shootable_charges {
	// GEN INTROSPECTOR enum class test_shootable_charges
	CYAN_CHARGE,
	PISTOL_CYAN_CHARGE,
	PRO90_CHARGE,
	STEEL_CHARGE,
	ORANGE_CHARGE,
	SHOTGUN_RED_CHARGE,
	ZAMIEC_CHARGE,
	SZTURM_CHARGE,
	DEAGLE_CHARGE,
	LEWSII_CHARGE,
	HPSR_CHARGE,
	BULLDUP2000_CHARGE,
	GALILEA_CHARGE,
	HUNTER_CHARGE,
	CYBERSPRAY_CHARGE,
	COVERT_CYAN_CHARGE,

	GRADOBICIE_CHARGE,
	SKULL_ROCKET,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_wandering_pixels_decorations {
	// GEN INTROSPECTOR enum class test_wandering_pixels_decorations
	WANDERING_PIXELS,

	AQUARIUM_PIXELS_LIGHT,
	AQUARIUM_PIXELS_DIM,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_hand_explosives {
	// GEN INTROSPECTOR enum class test_hand_explosives
	FORCE_GRENADE,
	PED_GRENADE,
	INTERFERENCE_GRENADE,
	FLASHBANG,

	BOMB,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_plain_missiles {
	// GEN INTROSPECTOR enum class test_plain_missiles
	CYAN_ROUND,
	PISTOL_CYAN_ROUND,
	STEEL_ROUND,
	LEWSII_ROUND,
	ORANGE_ROUND,
	SHOTGUN_RED_ROUND,
	PRO90_ROUND,
	ELECTRIC_MISSILE,
	AMPLIFIER_ARM_MISSILE,
	SKULL_ROCKET_FLYING,
	BLUNAZ_MISSILE,
	GRADOBICIE_ROUND,
	ZAMIEC_ROUND,
	SZTURM_ROUND,
	DEAGLE_ROUND,
	HPSR_ROUND,
	BULLDUP2000_ROUND,
	GALILEA_ROUND,
	HUNTER_ROUND,
	COVERT_CYAN_ROUND,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_finishing_traces {
	// GEN INTROSPECTOR enum class test_finishing_traces
	CYAN_ROUND_FINISHING_TRACE,
	STEEL_ROUND_FINISHING_TRACE,
	ORANGE_ROUND_FINISHING_TRACE,
	SHOTGUN_RED_ROUND_FINISHING_TRACE,
	PRO90_ROUND_FINISHING_TRACE,
	ELECTRIC_MISSILE_FINISHING_TRACE,
	GRADOBICIE_ROUND_FINISHING_TRACE,
	DEAGLE_ROUND_FINISHING_TRACE,
	HPSR_ROUND_FINISHING_TRACE,
	BULLDUP2000_ROUND_FINISHING_TRACE,
	GALILEA_ROUND_FINISHING_TRACE,
	HUNTER_ROUND_FINISHING_TRACE,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_container_items {
	// GEN INTROSPECTOR enum class test_container_items
	STANDARD_PERSONAL_DEPOSIT,

	BILMER2000_MAGAZINE,
	DATUM_GUN_MAGAZINE,
	BAKA47_MAGAZINE,
	KEK9_MAGAZINE,
	SN69_MAGAZINE,
	AO44_MAGAZINE,
	CALICO_MAGAZINE,
	PRO90_MAGAZINE,
	LEWSII_MAGAZINE,
	WARX_FQ12_MAGAZINE,
	BULWARK_MAGAZINE,
	ZAMIEC_MAGAZINE,
	SZTURM_MAGAZINE,
	DEAGLE_MAGAZINE,
	AWKA_MAGAZINE,
	BULLDUP2000_MAGAZINE,
	GALILEA_MAGAZINE,
	HUNTER_MAGAZINE,
	CYBERSPRAY_MAGAZINE,
	COVERT_MAGAZINE,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_dynamic_decorations {
	// GEN INTROSPECTOR enum class test_dynamic_decorations
	YELLOW_FISH,
	DARKBLUE_FISH,
	CYANVIOLET_FISH,
	JELLYFISH,
	DRAGON_FISH,
	RAINBOW_DRAGON_FISH,
	WATER_CAUSTICS,

	BUTTERFLY,
	CICADA,
	MOTA,

	FLOWER_PINK,
	FLOWER_CYAN,

	CYBER_PANEL,

	PINK_CORAL,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_remnant_bodies {
	// GEN INTROSPECTOR enum class test_remnant_bodies
	STEEL_ROUND_REMNANT_1,
	STEEL_ROUND_REMNANT_2,
	STEEL_ROUND_REMNANT_3,

	CYAN_SHELL,
	STEEL_SHELL,
	ORANGE_SHELL,
	SHOTGUN_RED_SHELL,
	PRO90_SHELL,
	SKULL_ROCKET_SHELL,
	GRADOBICIE_SHELL,
	DEAGLE_SHELL,

	LEWSII_ROUND_REMNANT_1,
	LEWSII_ROUND_REMNANT_2,
	LEWSII_ROUND_REMNANT_3,
	LEWSII_SHELL,

	HPSR_SHELL,
	BULLDUP2000_SHELL,
	GALILEA_SHELL,
	HUNTER_SHELL,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_sound_decorations {
	// GEN INTROSPECTOR enum class test_sound_decorations
	AQUARIUM_AMBIENCE_LEFT,
	AQUARIUM_AMBIENCE_RIGHT,

	POWERLINE_NOISE,
	LOUDY_FAN,

	ARABESQUE,
	GENERIC_BOMB_SOON_EXPLODES_THEME,

	FOOTSTEP_DIRT,
	FOOTSTEP_FLOOR,
	FOOTSTEP_AIR_DUCT,
	FOOTSTEP_FENCE,
	FOOTSTEP_STANDARD,

	PORTAL_AMBIENCE,
	PORTAL_BEGIN_ENTERING_SOUND,
	PORTAL_ENTER_SOUND,
	PORTAL_EXIT_SOUND,

	FIRE_DAMAGE,
	LAVA_AMBIENCE,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_particles_decorations {
	// GEN INTROSPECTOR enum class test_particles_decorations
	AQUARIUM_BUBBLES,
	FLOWER_BUBBLES,

	WANDERING_SMOKE,

	GLASS_DAMAGE,
	METAL_DAMAGE,
	WOOD_DAMAGE,
	EXHAUSTED_SMOKE,
	DASH_SMOKE,

	PORTAL_CIRCLE,
	PORTAL_BEGIN_ENTERING_PARTICLES,
	PORTAL_ENTER_PARTICLES,
	PORTAL_EXIT_PARTICLES,

	LAVA_CIRCLE,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_point_markers {
	// GEN INTROSPECTOR enum class test_point_markers
	TEST_TEAM_SPAWN,
	COUNT
	// END GEN INTROSPECTOR
};

enum class test_area_markers {
	// GEN INTROSPECTOR enum class test_area_markers
	BOMBSITE_A,
	BUY_AREA,

	ORGANISM_AREA,

	CALLOUT_T_SPAWN,
	CALLOUT_CT_SPAWN,
	CALLOUT_ROOM,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_explosion_bodies {
	// GEN INTROSPECTOR enum class test_explosion_bodies
	BOMB_CASCADE_EXPLOSION,
	BOMB_CASCADE_EXPLOSION_SMALLER,

	FORCE_GRENADE_CASCADE,

	SKULL_ROCKET_CASCADE,
	SKULL_ROCKET_CASCADE_SMALLER,

	INTERFERENCE_CASCADE,

	ELECTRIC_MISSILE_CASCADE,
	ELECTRIC_MISSILE_CASCADE_SMALLER,

	BLUNAZ_MISSILE_CASCADE,
	BLUNAZ_MISSILE_CASCADE_SMALLER,

	METROPOLIS_CORPSE_EXPLOSION_CASCADE,
	RESISTANCE_CORPSE_EXPLOSION_CASCADE,

	COUNT
	// END GEN INTROSPECTOR
};

enum class test_tool_items {
	// GEN INTROSPECTOR enum class test_tool_items
	METROPOLIS_BACKPACK,
	RESISTANCE_BACKPACK,

	DEFUSE_KIT,
	ELECTRIC_ARMOR,

	COUNT
	// END GEN INTROSPECTOR
};

