#pragma once

enum class main_menu_button_type {
	// GEN INTROSPECTOR enum class main_menu_button_type
	CONNECT_TO_OFFICIAL_UNIVERSE,
	BROWSE_COMMUNITY_SERVERS,
	HOST_UNIVERSE,
	CONNECT_TO_UNIVERSE,
	LOCAL_UNIVERSE,
	EDITOR,
	SETTINGS,
	CREATORS,
	QUIT,

	COUNT
	// END GEN INTROSPECTOR
};