#!/usr/bin/env bash 
CONFIGURATION=$1
ARCHITECTURE=$2

if [[ -z "$ARCHITECTURE" ]]
then
	ARCHITECTURE="x64"
fi

TARGET_DIR="build/${CONFIGURATION}-${ARCHITECTURE}"
echo "Building into $TARGET_DIR"

mkdir --parents $TARGET_DIR
pushd $TARGET_DIR
cmake -DUNIX=ON -DBUILD_IN_CONSOLE_MODE=1 -DARCHITECTURE=$ARCHITECTURE -DCMAKE_BUILD_TYPE=$CONFIGURATION ${OLDPWD}
popd
