#!/usr/bin/env bash 
CONFIGURATION=$1
ARCHITECTURE=$2

if [[ -z "$ARCHITECTURE" ]]
then
	ARCHITECTURE="x64"
fi

TARGET_DIR="build/${CONFIGURATION}-${ARCHITECTURE}"
echo "Building into $TARGET_DIR"

mkdir --parents $TARGET_DIR
cd $TARGET_DIR
cmake -DARCHITECTURE=$ARCHITECTURE -DCMAKE_BUILD_TYPE=$CONFIGURATION $3 $OLDPWD
