#pragma once
#define ENABLE_POLYGONIZATION_IN_DEBUG 1
#define ENABLE_POLYGONIZATION_IN_RELEASE 1

#define ENABLE_POLYGONIZATION ((_DEBUG || NDEBUG) ? ENABLE_POLYGONIZATION_IN_DEBUG : ENABLE_POLYGONIZATION_IN_RELEASE)
