#pragma once
#define ENABLE_POLYGONIZATION_IN_DEBUG 0
#define ENABLE_POLYGONIZATION_IN_RELEASE 0

#define ENABLE_POLYGONIZATION ((_DEBUG || NDEBUG) ? ENABLE_POLYGONIZATION_IN_DEBUG : ENABLE_POLYGONIZATION_IN_RELEASE)
