#pragma once

enum class match_command {
	// GEN INTROSPECTOR enum class match_command
	RESTART_MATCH,
	RESTART_MATCH_NO_WARMUP,
	SWAP_TEAMS,
	SCRAMBLE_TEAMS,

	TEST_ANNOUNCE_DUEL,
	TEST_ANNOUNCE_MATCH_RESULT,

	COUNT
	// END GEN INTROSPECTOR
};
