#pragma once

enum class processing_subjects {
	WITH_ANIMATION,
	WITH_BEHAVIOUR_TREE,
	WITH_CAR,
	WITH_CROSSHAIR,
	WITH_DAMAGE,
	WITH_DRIVER,
	WITH_FORCE_JOINT,
	WITH_GUI_ELEMENT,
	WITH_INPUT_RECEIVER,
	WITH_ITEM_SLOT_TRANSFERS,
	WITH_MELEE,
	WITH_GUN,
	WITH_MOVEMENT,
	WITH_PARTICLE_GROUP,
	WITH_PATHFINDING,
	WITH_POSITION_COPYING,
	WITH_ROTATION_COPYING,
	WITH_SENTIENCE,
	WITH_TRACE,
	WITH_TRIGGER_QUERY_DETECTOR,
	WITH_VISIBILITY,
	LIST_COUNT
};
