name: MacOS build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Install p7zip
      run: brew install p7zip
    - name: Install ImageMagick for create-dmg
      run: brew install graphicsmagick imagemagick
    - name: Install create-dmg
      run: npm install --global create-dmg
    - name: Install ninja
      run: brew install ninja
    - name: Install sodium
      run: brew install libsodium
    - name: Generate CMake files
      run: export LDFLAGS="-framework Cocoa -framework IOKit -framework CoreFoundation" && cmake/build.sh Release x64 '-DUSE_GLFW=1 -DGENERATE_DEBUG_INFORMATION=0 -DBUILD_DEBUGGER_SETUP=0 -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl'
    - name: Build
      run: pushd build/current && ninja tests -k 0 && popd
    - name: Generate downloadable archives
      run: cmake/generate_archives.sh MacOS master

    - uses: actions/upload-artifact@v3
      with:
        name: MacOS-binaries
        path: |
          Hypersomnia-for-*
          hypersomnia/release_notes.txt
