#pragma once
#include "systems/physics_system.h"
#include "systems/steering_system.h"
#include "systems/movement_system.h"
#include "systems/visibility_system.h"
#include "systems/pathfinding_system.h"
#include "systems/animation_system.h"
#include "systems/camera_system.h"
#include "systems/render_system.h"
#include "systems/input_system.h"
#include "systems/gun_system.h"
#include "systems/crosshair_system.h"
#include "systems/rotation_copying_system.h"
#include "systems/position_copying_system.h"
#include "systems/damage_system.h"
#include "systems/destroy_system.h"
#include "systems/particle_group_system.h"
#include "systems/particle_emitter_system.h"
#include "systems/behaviour_tree_system.h"
#include "systems/car_system.h"
#include "systems/driver_system.h"
#include "systems/trigger_detector_system.h"
#include "systems/item_system.h"
#include "systems/force_joint_system.h"
#include "systems/intent_contextualization_system.h"
#include "systems/gui_system.h"




