#pragma once
#include "messages/destroy_message.h" 
#include "messages/collision_message.h"
#include "messages/intent_message.h"
#include "messages/animation_message.h"
#include "messages/animation_response_message.h"
#include "messages/particle_burst_message.h"
#include "messages/damage_message.h"
#include "messages/shot_message.h"
#include "messages/raw_window_input_message.h"
#include "messages/unmapped_intent_message.h"
#include "messages/crosshair_intent_message.h"
#include "messages/trigger_hit_confirmation_message.h"
#include "messages/trigger_hit_request_message.h"
#include "messages/new_entity_message.h"
#include "messages/camera_render_request_message.h"
#include "messages/item_slot_transfer_request.h"

